services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=bancodesangue'
      - 'MYSQL_PASSWORD=Pamonha123*'
      - 'MYSQL_ROOT_PASSWORD=Marmanga123*'
      - 'MYSQL_USER=bdsangue'
    ports:
      - '3306'
