services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${BASE}'
      - 'MYSQL_PASSWORD=${PWD}'
      - 'MYSQL_ROOT_PASSWORD=${PWD}'
      - 'MYSQL_USER=${DB_USERNAME}'
    ports:
      - '3306:3306'
