spring.application.name=bancodesangue

##BANCO###
spring.datasource.url=jdbc:mysql://localhost:3306/bancodesangue
spring.datasource.username=bdsangue
spring.datasource.password=Pamonha123*
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

